// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeqvgveixtxzumvhigth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcXZndmVpeHR4enVtdmhpZ3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDI2ODAsImV4cCI6MjA3NDI3ODY4MH0.K2bGDwcBQpLshQe8jQJQwKPmMLTeSkWmROONdamq6Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});